# Stage 1: Dependencies
FROM node:18 AS deps
WORKDIR /app
COPY package.json ./
RUN yarn install

# Stage 2: Runner
FROM node:18 AS runner
WORKDIR /app

# Copy package.json and dependencies
COPY --from=deps /app/node_modules ./node_modules
COPY ./package.json ./package.json

# Copy application files
COPY ./public ./public
COPY ./src ./src

# Create a non-root user
RUN groupadd -g 1001 nodejs
RUN useradd -u 1001 -g nodejs nodeuser
USER nodeuser

EXPOSE 3000

CMD ["yarn", "start"]